### ISSUE TITLE
There are some bugs

### ISSUE THREAD

**Issue by Composer-Hu** [blarp5090/BWSB#1]
Thank you for making this datapack! This is really make wither storm more stronger.But there are some problems, when wither storm phase be redstonenia, it will burrow into the ground, and will get stuck inside and not track the player, and formidibomb shouldn't be included in the entity you force pull. In the state of suspended animation of the wither storm, it wakes up immediately the moment it is approached, with no buffer time, I don't know if this is a bug or a deliberate design, but it's really make me suprised.

Next are some suggestions：Maybe you can make the flaming wither skull shoot more often? Or have a greater explosive range, higher damage. Let the tractor beam pull entity faster(Of course I know this is very difficult, so it's just an idea, or maybe it will be implement in the future)

By the way, English is not my native language, Please forgive me for the grammatical error！

**Comment by WitherBean** [comment]
In the next update I will fix the bugs and the wither storm activating when players get close is a feature. Thank you for this information and the formidibomb changes will be in the next update. I will try to increase the tractor beam pull speed and the flaming wither skull explosive range and damage.

**Comment by Composer-Hu** [comment]
Thank You!

**Comment by WitherBean** [comment]
Your welcome!

**Comment by WitherBean** [comment]
I have just finished updating the flaming wither skull and the update will up soon.

**Comment by Composer-Hu** [comment]
Great, You are my God!

**Comment by WitherBean** [comment]
Thank you, the update will be out in a few minutes.

**Comment by WitherBean** [comment]
The update has been released.

**Comment by Composer-Hu** [comment]
I see it, thank you!

**Comment by WitherBean** [comment]
Your welcome

**Comment by WitherBean** [comment]
Have you fought the command block?

**Comment by Composer-Hu** [comment]
Yes, of course

**Comment by WitherBean** [comment]
I will close this issue but if you find anymore issues, please let me know.

**Comment by Composer-Hu** [comment]
Ok!
