### ISSUE TITLE
functions 

### ISSUE THREAD

**Issue by hodgettsalf1** [blarp5090/BWSB#10]
hey in the new update for the bwsm some of the functions dont work like nightglare and they all dont activate. i aint sure if its me whos using them wrong or they wont work. Please can u try telling me how to fix this

**Comment by WitherBean** [comment]
Which functions?

**Comment by hodgettsalf1** [comment]
ride head, swing, rotrate, night glare

**Comment by WitherBean** [comment]
These functions are just meant to be used for the tick.mcfunction file.
Rotate is unused, so it will be removed.
Swing was originally used for tentacles hitting mobs.
Nightglare was removed due to the CWSM update.
Ride Head is used to ride the Wither Storm heads, this is meant to be running on repeat and near a Wither Storm head.

**Comment by hodgettsalf1** [comment]
Oh okay but will the witherstorm commandblock be able to go upside down still bc i would personally like it

**Comment by WitherBean** [comment]
The command block already can flip upside down.

**Comment by hodgettsalf1** [comment]
for me it dont it just stays the same like normal and coverred by tentacles

**Comment by WitherBean** [comment]
It only flips when it is one hit from death and what version are you playing?

**Comment by hodgettsalf1** [comment]
1.18.2 
i struggle running 1.19+ with the mod idk why

**Comment by WitherBean** [comment]
Are you running 4.0.0 of BWSB or lower?

**Comment by hodgettsalf1** [comment]
4.0.0

**Comment by WitherBean** [comment]
Are you able to get a screenshot for me to help you?

**Comment by hodgettsalf1** [comment]
yes i have one

**Comment by WitherBean** [comment]
Please post it here.

**Comment by hodgettsalf1** [comment]
okay

**Comment by hodgettsalf1** [comment]
![Uploading Java-runtime-beta Screenshot 2023.03.18 - 17.43.07.52.png…]()

**Comment by hodgettsalf1** [comment]
the files r uploading

**Comment by hodgettsalf1** [comment]
image i meant

**Comment by hodgettsalf1** [comment]
![Uploading Java-runtime-beta Screenshot 2023.03.18 - 17.43.07.52.png…]()

**Comment by hodgettsalf1** [comment]
do u have discord i dont think the image is being sent

**Comment by WitherBean** [comment]
I do not have discord, but you could upload to Imgur?

**Comment by hodgettsalf1** [comment]
it says not availible in ur region

**Comment by hodgettsalf1** [comment]
try this idk
https://imgur.com/a/kDtv7o8

**Comment by hodgettsalf1** [comment]
oh there

**Comment by WitherBean** [comment]
What mods do you have installed?

**Comment by hodgettsalf1** [comment]
rubidium, cwsm, ferrite core, pehkui and olivers mcsm armour

**Comment by WitherBean** [comment]
I have only tested the datapack with pehkui, optifine, and CWSM. Maybe the other mods are doing something to change this. Try removing the other mods.

**Comment by hodgettsalf1** [comment]
nope. nothing has worked

**Comment by WitherBean** [comment]
Try /datapack list available or /datapack list enabled. A message should come back that says file/bwsb(world) or something that has bwsb in it.

**Comment by hodgettsalf1** [comment]
yes i do that
so i can use the datapack

**Comment by WitherBean** [comment]
Are any other functions available?

**Comment by hodgettsalf1** [comment]
none of them work like bowels dont fall apart until i use the command

**Comment by hodgettsalf1** [comment]
the f bomb works recipe and the stage ones work

**Comment by hodgettsalf1** [comment]
like redstonia, f bomb battle, overgrown

**Comment by hodgettsalf1** [comment]
and devourer

**Comment by WitherBean** [comment]
The bowels is not supposed to fall apart anymore and when you use the function commands, make sure that a Wither Storm is active.

**Comment by hodgettsalf1** [comment]
oh

**Comment by hodgettsalf1** [comment]
i guess that i might need to try fix the command block not going upside down then

**Comment by hodgettsalf1** [comment]
and so it does

**Comment by WitherBean** [comment]
It flips now?

**Comment by hodgettsalf1** [comment]
no

**Comment by hodgettsalf1** [comment]
i dont know why it wont

**Comment by hodgettsalf1** [comment]
nothing to do w the mods

**Comment by WitherBean** [comment]
Try to hit the command block three times, so it is at the last quarter of its health.

**Comment by hodgettsalf1** [comment]
thats what i do it just uses the tentacles as the shield

**Comment by Composer-Hu** [comment]
Did you download the pre-mod pehkui? Without it, the datapack will not work.

**Comment by hodgettsalf1** [comment]
i have 1.18.2

**Comment by Composer-Hu** [comment]
Your datapack is completely ineffective, or just something worng?

**Comment by hodgettsalf1** [comment]
the formidi bomb reciple with 8 gunpowder works thats what i know

**Comment by hodgettsalf1** [comment]
it still wont work

**Comment by Composer-Hu** [comment]
Which part doesn't work?

**Comment by hodgettsalf1** [comment]
command block flipping

**Comment by Composer-Hu** [comment]
It's not really a flip, It's just that it's hard for data packages to implement this, but it will make the command block fly to the top. This achieves the effect of reversal in disguise

**Comment by WitherBean** [comment]
What comes up when you type "/function bwsb:"?

**Comment by hodgettsalf1** [comment]
all cmds

**Comment by WitherBean** [comment]
Then the datapack is enabled, but it might not be active.

**Comment by WitherBean** [comment]
Does anything else work?

**Comment by hodgettsalf1** [comment]
the stage ones do so does particles

**Comment by hodgettsalf1** [comment]
and creeper cure

**Comment by WitherBean** [comment]
Try either re-downloading or saving and quitting the world, then entering back in.

**Comment by hodgettsalf1** [comment]
i do that then when i join it says safe mode or back to title 
so i re enable the mod

**Comment by WitherBean** [comment]
I think that means that the world no longer works.

**Comment by hodgettsalf1** [comment]
i tried other worlds aswell and its technically the same

**Comment by WitherBean** [comment]
Is Witherstormmod New Textures 2.0.0 enabled?

**Comment by Composer-Hu** [comment]
If you are free, try installing more than one version, and just with mods:CWSM, pehkui, optifine? This's just a test.

**Comment by hodgettsalf1** [comment]
yes textures r enabled

**Comment by hodgettsalf1** [comment]
the texture dont impact it bc ive used the datapack longer than textures

**Comment by WitherBean** [comment]
The textures also add sounds, which adds more features to the datapack.

**Comment by hodgettsalf1** [comment]
yes, dynamic sounds, and i found a bug when the bowels ambience just cuts out and repeats

**Comment by hodgettsalf1** [comment]
and it says dat pack validation failed which rlly annoys me

**Comment by WitherBean** [comment]
That might be why...

**Comment by hodgettsalf1** [comment]
idk how to fix this stuff tbh

**Comment by WitherBean** [comment]
What CWSM version are you using?

**Comment by hodgettsalf1** [comment]
a block and a hard place {1.18.2}

**Comment by hodgettsalf1** [comment]
r u able to try make the bwsm 4.0.0 a version for 1.18.2 if that fixes the problem

**Comment by WitherBean** [comment]
The datapack's pack.mcmeta version is 12, which is 1.19.3 so maybe that is why.

**Comment by hodgettsalf1** [comment]
oh but my pc aint good at running at 1.19+ idk why

**Comment by WitherBean** [comment]
I am uploading the bug fix now.

**Comment by hodgettsalf1** [comment]
thank u so much

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
In a few minutes, it will be released.

**Comment by hodgettsalf1** [comment]
okay, does it have the 1.18.2 version bc i think its the reason that it aint the actual version

**Comment by WitherBean** [comment]
It is 1.18.2.

**Comment by WitherBean** [comment]
You can now download it.

**Comment by hodgettsalf1** [comment]
alr thank u

**Comment by WitherBean** [comment]
You're welcome!

**Comment by hodgettsalf1** [comment]
i'll see if it works and i'd pray for the stupidmessage to not come up

**Comment by hodgettsalf1** [comment]
i keep geting the message but ive put it in a world ive made and now it says safe mode

**Comment by hodgettsalf1** [comment]
hey there crackers said its the data pack thats the problem

**Comment by hodgettsalf1** [comment]
i have a log file i can show

**Comment by hodgettsalf1** [comment]
[latest.log](https://github.com/WitherBean/BWSB/files/11030983/latest.log)

**Comment by WitherBean** [comment]
Download a newer version of Witherstormmod New Textures (WNT), preferably 2.5.0.

**Comment by hodgettsalf1** [comment]
i have

**Comment by hodgettsalf1** [comment]
it still says data pack validation failed

**Comment by WitherBean** [comment]
[20Mar2023 18:08:49.720] [Render thread/WARN] [net.minecraft.server.packs.repository.Pack/]: Couldn't find pack meta for pack file/3dStoryModeCommandBlocks1.19.zip

Looks like it is other resource packs.

**Comment by hodgettsalf1** [comment]
ohhh

**Comment by hodgettsalf1** [comment]
nvm it aint

**Comment by hodgettsalf1** [comment]
[latest.log](https://github.com/WitherBean/BWSB/files/11033174/latest.log)

**Comment by WitherBean** [comment]
Remove all of the resource packs besides Witherstormmod New Textures 2.5.0.

**Comment by hodgettsalf1** [comment]
ok

**Comment by hodgettsalf1** [comment]
Ok i meaan

**Comment by hodgettsalf1** [comment]
[latest.log](https://github.com/WitherBean/BWSB/files/11033301/latest.log)

**Comment by hodgettsalf1** [comment]
idk why it says rubidium is the problem it helps me run good fps

**Comment by WitherBean** [comment]
Try removing it.

**Comment by hodgettsalf1** [comment]
i have

**Comment by hodgettsalf1** [comment]
no work

**Comment by hodgettsalf1** [comment]
i deleted my mods and i got it again
but different

**Comment by hodgettsalf1** [comment]
[latest.log](https://github.com/WitherBean/BWSB/files/11054723/latest.log)

**Comment by WitherBean** [comment]
What is the forge version?

**Comment by WitherBean** [comment]
It cannot validate the datapack.

**Comment by hodgettsalf1** [comment]
1.18.2 40.2.0

**Comment by hodgettsalf1** [comment]
i use 40.2.1 and still same

**Comment by hodgettsalf1** [comment]
i'll try 1.19.3

**Comment by WitherBean** [comment]
Do you have Optifine 1.19.3?

**Comment by WitherBean** [comment]
(preview)

**Comment by hodgettsalf1** [comment]
no i dont

**Comment by WitherBean** [comment]
try this: https://www.youtube.com/watch?v=-pX-2EYIITk

**Comment by hodgettsalf1** [comment]
hey there i have very good news

**Comment by hodgettsalf1** [comment]
with 1.19.3 the datapack works
