### ISSUE TITLE
About the health bar UI texture

### ISSUE THREAD

**Issue by lonely734** [blarp5090/BWSB#11]
Hello, I feel the original blood bar it's a little unworthy of such a behemoth as the withering storm
Can you modify a more domineering health bar?
Just like this
![filled_wither_storm_bar](https://user-images.githubusercontent.com/127328952/226188784-0d4119c1-3908-4ca8-8faa-3e776e0b39b2.png)
![empty_wither_storm_bar](https://user-images.githubusercontent.com/127328952/226188788-42287dd3-5d80-47c6-8a63-0df637725c61.png)

**Comment by WitherBean** [comment]
I will do this a little differently, but this will be added in the next update (Witherstormmod New Textures).

**Comment by lonely734** [comment]
That's so cool

**Comment by WitherBean** [comment]
This has been added in Witherstormmod New Textures 2.5.0.
