### ISSUE TITLE
Withered Moon

### ISSUE THREAD

**Issue by NinjaSam5399** [blarp5090/BWSB#12]
I don't know if there is a Withered Moon. But, if there is none can you add it, instead of just Withered Sun? And also, the Withered Moon also has the same ambience thing with the Withered Sun.

**Comment by NinjaSam5399** [comment]
You should add it in the next update.

**Comment by NinjaSam5399** [comment]
Well, the issues in the suggestion in Nonamecrackers2 GitHub page are closed, but here's the picture. 
![image](https://user-images.githubusercontent.com/111523734/226403888-1bda4433-e15e-4314-89b0-dcf4c76bdd0b.png)

**Comment by NinjaSam5399** [comment]
Also in phases of the moon. 
![image](https://user-images.githubusercontent.com/111523734/226409658-425bdb0d-7e3b-420e-80fc-8929400ae308.png)

**Comment by NinjaSam5399** [comment]
Heres also the sound. (Do it in loops.) https://youtu.be/HeKQS1dW3rg

**Comment by WitherBean** [comment]
The Withered Moon is being worked on right now.

**Comment by WitherBean** [comment]
The Withered Moon has been completed.

**Comment by NinjaSam5399** [comment]
Thanks
