### ISSUE TITLE
Improved tentacles in phase 6.

### ISSUE THREAD

**Issue by NinjaSam5399** [blarp5090/BWSB#13]
I am not suggesting it to be more blocky or put its tentacles in the nether portal. I'm just suggesting making one new tentacle and improving the tentacles to look more like story mode. Here is the picture that I copied from your picture (I'm too lazy to make my own).
 
The picture (Ignore the tractor beams from phase 7): 
![image](https://user-images.githubusercontent.com/111523734/227057318-43d1e50e-77b4-43d5-99dd-fd61ef994e80.png)

**Comment by WitherBean** [comment]
Would this look good for the segments?
![tentacles](https://user-images.githubusercontent.com/114886300/227336715-2109ddd7-e101-408c-93e5-196186ee4270.png)

**Comment by NinjaSam5399** [comment]
Oh yes, thats the best for the segment.

**Comment by NinjaSam5399** [comment]
Except the tentacles above the third wither storm head seems like it is floating.

**Comment by WitherBean** [comment]
I tried this, but it looks horrible when the Wither Storm spawns.

**Comment by NinjaSam5399** [comment]
ok
