### ISSUE TITLE
About Tractor Beam

### ISSUE THREAD

**Issue by Composer-Hu** [blarp5090/BWSB#14]
In the new update 4.5.0, I experienced a better tractor beam, you modified the mechanism by which creatures are quickly teleported, make the creature more like it was pulled by a tractor beam. 

I don't understand this, but I want to ask is the head outside of the withering storm as an optional entity in the command? If you can, I ask you to modify it to be absorbed by different heads, and not just absorbed by the middle head. If you have determined that this is not feasible, you can just turn it off, thanks.

**Comment by WitherBean** [comment]
This is possible, but it could not be in the next update.

**Comment by Composer-Hu** [comment]
Thank you for being willing to try this!

**Comment by Composer-Hu** [comment]
Excuse me, I found something in the April Fool's 23w13a_or_b version, it's about the function of a supermoon, as it gets bigger, the gravitational pull also increases and attracts creatures to fly towards it. I thought maybe this could help you improve the tractor beam?

**Comment by WitherBean** [comment]
I will look into this.

**Comment by Composer-Hu** [comment]
Thank you.

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
I could do raytracing.

**Comment by Composer-Hu** [comment]
Thanks, but the next cracker update has a new configuration item that satisfies this, so you don't need to go to the trouble of remaking it.
