### ISSUE TITLE
The hole still appears even though its in phase 4.

### ISSUE THREAD

**Issue by NinjaSam5399** [blarp5090/BWSB#15]
Heres the Picture: 
![2023-03-23_22 17 05](https://user-images.githubusercontent.com/111523734/227365403-78421003-c68c-4609-9237-026f8a68ba60.png)

**Comment by NinjaSam5399** [comment]
Do you see the hole

**Comment by WitherBean** [comment]
Yes, what are the errors?

**Comment by WitherBean** [comment]
This is not a bug, but this only happens because there is an enderman nearby. If it would be better, the hole could appear only in phase 7.

**Comment by NinjaSam5399** [comment]
ok
