### ISSUE TITLE
Two texture requests

### ISSUE THREAD

**Issue by Composer-Hu** [blarp5090/BWSB#16]
1. About pulling particles in a beam: In MCSM, the color transparency of particles is high, can you make particles more transparent? And if you can, please make the particles more denser, just like MCSM
![}BOW0Q}FPA%B X)V6YRGEW4](https://user-images.githubusercontent.com/127498588/227497860-29def2c2-cc6c-4fce-ab6d-674ea5e97d3e.png)

2. About the shine: can you make the aperture more transparent as well? Even the edges have a fade-out effect.

Thank you！

**Comment by Composer-Hu** [comment]
![$L$(92)I8ZEN$%3JRDJO_8](https://user-images.githubusercontent.com/127498588/227498827-56a33e0b-1e29-4524-99c9-e9d28e1607ce.png)

**Comment by WitherBean** [comment]
I cannot make them denser, but I can make them transparent.

**Comment by Composer-Hu** [comment]
No problem, but can the glare change? The second point I mean is this.

**Comment by WitherBean** [comment]
The night glare can change but the more white or transparent it gets, it becomes more purple.

**Comment by Composer-Hu** [comment]
Ah, I see, the current glare opaque is to cover the original glare?

**Comment by WitherBean** [comment]
The current one is not opaque.

**Comment by Composer-Hu** [comment]
Can you just do this, the edges partially fade out?

**Comment by WitherBean** [comment]
I believe so, but it will be in the next update of Witherstormmod New Textures.

**Comment by Composer-Hu** [comment]
Thank you very much.

**Comment by Composer-Hu** [comment]
Thank you very much.

**Comment by Composer-Hu** [comment]
Thank you！

**Comment by WitherBean** [comment]
You're welcome!

**Comment by Composer-Hu** [comment]
Sorry, my network is stuck.

**Comment by WitherBean** [comment]
It's okay.
