### ISSUE TITLE
3d F bomb and 3d Super TNT

### ISSUE THREAD

**Issue by hodgettsalf1** [blarp5090/BWSB#17]
i was wondering if you could do the 3d f bomb and 3d super tnt from mcsm episode 3
![f bomb](https://user-images.githubusercontent.com/128244555/228299909-961635e0-759c-460f-b57e-1a02b8c3e94f.jpg)

**Comment by hodgettsalf1** [comment]
and this as super tnt
![super tnt](https://user-images.githubusercontent.com/128244555/228300489-d493d083-555c-45cb-a10f-3a2d214112d2.jpg)

**Comment by WitherBean** [comment]
The formidibomb is almost done and the super TNT has just been finished.

**Comment by WitherBean** [comment]
The formidibomb is almost done and the super TNT has just been finished.

**Comment by hodgettsalf1** [comment]
alr

**Comment by Composer-Hu** [comment]
Maybe there are 3D command blocks? The command block from the last update is not like this one, although it is also good.

**Comment by Composer-Hu** [comment]
![Cache_-79446a7da64527f6](https://user-images.githubusercontent.com/127498588/228410086-576b70e8-3f49-47c8-8f61-ab9d0f18aefb.jpg)

**Comment by Composer-Hu** [comment]
![3d_command_block](https://user-images.githubusercontent.com/127498588/228410782-befa1b6a-7655-49c9-8782-bf44e88afcfb.png)
Maybe you can use this sticker？

**Comment by Composer-Hu** [comment]
Excuse me, do you have any plans to continue doing 3D command blocks and formidibomb, the last update of Super TNT was really fantastic！

**Comment by Composer-Hu** [comment]
![QQ图片20230409201801](https://user-images.githubusercontent.com/127498588/230772089-8c7177e4-43c7-424b-8d1e-0243e976ac1b.png)
![QQ图片20230409201809](https://user-images.githubusercontent.com/127498588/230772090-a30d5884-b5f4-40b7-a07c-c410e97bccb2.png)
![QQ图片20230409201821](https://user-images.githubusercontent.com/127498588/230772091-829722c6-466b-456b-8e08-974c0da37c4a.png)
![QQ图片20230409201828](https://user-images.githubusercontent.com/127498588/230772094-5d7d2a03-1c29-4e16-a0b6-04e9c7ad8b46.png)
Even a 3D command block book. You don't need to rush, I'll just leave it here for now.

**Comment by WitherBean** [comment]
Maybe in the upcoming BWSB update. Re-open this if you would like more 3D models in Witherstormmod New Textures.
