### ISSUE TITLE
BWSB: Miniboss Ideas

### ISSUE THREAD

**Issue by WitherBean** [blarp5090/BWSB#18]
A new miniboss is being added to BWSB 5.0.0. It's attacks consist of summoning mobs to protect itself and shooting arrows with the flame and power enchantments. When it is at half health, it can heal and summon lightning on top of players and other mobs. Does anybody have anymore ideas for this boss? If anybody wants to, you could make or find any boss themes that would sound good for this boss.

**Comment by Composer-Hu** [comment]
Maybe it will indiscriminately attack creatures outside the CWSM mod?

**Comment by NinjaSam5399** [comment]
Nice

**Comment by NinjaSam5399** [comment]
Let's call it the Withered Golem.

**Comment by NinjaSam5399** [comment]
https://youtu.be/TlgKLwmZnoQ This theme could be good.

**Comment by WitherBean** [comment]
I would have to get permission to use this song, but I could use or make another one.

**Comment by NinjaSam5399** [comment]
oh ok

**Comment by WitherBean** [comment]
I have gotten boss music for this and it was made by somebody via discord.

**Comment by WitherBean** [comment]
closed until further notice
