### ISSUE TITLE
About become wither storm

### ISSUE THREAD

**Issue by Composer-Hu** [blarp5090/BWSB#19]
Make a suggestion for improvement: Now after using the command /function bwsb:becomewitherstorm, the wither storm will constantly move above your head. But there is a problem, the fifth stage and later stage will cause the view to be obscured by tentacles growing underneath, and it's a pity, I couldn't clearly observe the WS above my head absorb everything. So can I request that the player be placed above the withering storm instead, or in front of its head? That would be cool.

**Comment by Composer-Hu** [comment]
Maybe it's more like an admin controlling a super robot haha.

**Comment by WitherBean** [comment]
I could do this but, it will not be in this update because I will be resealing it shortly.

**Comment by Composer-Hu** [comment]
Ok no problem.
