### ISSUE TITLE
withered symbiont strengthen

### ISSUE THREAD

**Issue by lonely734** [blarp5090/BWSB#2]
Can you give withered symbiont more skills?

**Comment by WitherBean** [comment]
Yes, but do you have any ideas?

**Comment by lonely734** [comment]
Such as adding a big explosion

**Comment by WitherBean** [comment]
Should that happed when it is killed or as an attack?

**Comment by lonely734** [comment]
that happened when it is killed

**Comment by Composer-Hu** [comment]
Or maybe he(even Sickened mobs) will attack all creatures indiscriminately？（Apart from the creatures in the CWSM mod）

**Comment by lonely734** [comment]
Maybe he can summon some other creatures

**Comment by WitherBean** [comment]
Ok, that will be in the next update...
I can add both of these.

**Comment by Composer-Hu** [comment]
Thank You, don't be too tired, don't rush

**Comment by WitherBean** [comment]
In the next update the Withered Symbiont will be able to place/destroy blocks, summon other sickened mobs, and explode when defeated. Anything else or is that it?

**Comment by lonely734** [comment]
Maybe he can recover some blood

**Comment by WitherBean** [comment]
That is a good idea.

**Comment by WitherBean** [comment]
I just finished the Withered Symbiont placing blocks.

**Comment by lonely734** [comment]
This will be a cool data package:)

**Comment by Composer-Hu** [comment]
Yes, it's very great!

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
Witherstormmod New Textures has been updated too!

**Comment by lonely734** [comment]
cool

**Comment by WitherBean** [comment]
Thank you!

**Comment by Composer-Hu** [comment]
Just don't get too tired and don't rush, you and your databack All great！

**Comment by WitherBean** [comment]
I just found an nbt tag on the Withered Symbiont called NextSpellPick...
I wonder what this does :)

**Comment by Composer-Hu** [comment]
Maybe it means preparing for the next skill?

**Comment by WitherBean** [comment]
I think so, which means I can control it's spells for the boss battle.

**Comment by WitherBean** [comment]
I will be taking a break soon, so I will not be able to answer some questions.

**Comment by Composer-Hu** [comment]
Yes, that's right, and thanks again

**Comment by WitherBean** [comment]
Your welcome, I will be back later.

**Comment by WitherBean** [comment]
I have returned.

**Comment by Composer-Hu** [comment]
I just tried the new resourcepacks and datapack,they are all great. And I don't think I should be too greedy for too many features in the short term.On my side, it's two in the morning, so I had to go to bed, so sorry.

**Comment by WitherBean** [comment]
It's okay, but what do you want to added?

**Comment by lonely734** [comment]
Maybe  can make the attack of  sickened creatures have a withered effect

**Comment by WitherBean** [comment]
I will try that...

**Comment by lonely734** [comment]
But I have no questions to ask now

**Comment by lonely734** [comment]
The update will bring some surprises:)

**Comment by WitherBean** [comment]
It will...

**Comment by WitherBean** [comment]
I am thinking about improving the wither storm re-summoning mechanic.

**Comment by WitherBean** [comment]
In the latest update, have you stood on the sickened mob statues?

**Comment by lonely734** [comment]
Yes

**Comment by WitherBean** [comment]
Was it a surprise when the mob spawned?

**Comment by WitherBean** [comment]
I just realized how powerful the new Wither Storm is.

**Comment by lonely734** [comment]
Yes, very powerful

**Comment by lonely734** [comment]
Can be weakened appropriately

**Comment by WitherBean** [comment]
What if the Withered Symbiont can through TNT?

**Comment by lonely734** [comment]
can

**Comment by lonely734** [comment]
On my side ，It's very late. I have to go to bed first

**Comment by WitherBean** [comment]
Ok, goodnight.

**Comment by lonely734** [comment]
I hope to see your update when I get up :)

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
Bad news, I cannot get the flaming wither skull to work because it crashes the game.

**Comment by WitherBean** [comment]
But I have some good news, It is that I am working on the death animation for the Wither Storm.

**Comment by WitherBean** [comment]
For the next update, you will need Pehkui.

**Comment by WitherBean** [comment]
This is the new Sickened Sun theme: https://www.youtube.com/watch?v=dnMKIjBCySo&list=PLk1sle6PCaD25UMPaxlaR3qI0uddeTvwK&index=28

**Comment by Composer-Hu** [comment]
Can you weaken the particle effects of formidibomb and command blocks? They were so dazzling, especially after being upside down, that I had difficulty finding command blocks.

**Comment by WitherBean** [comment]
I just weakened the command block particles.

**Comment by Composer-Hu** [comment]
Yes, that would be much better, by the way, you are amazing!I hope that one day your technology is mature and you can make mods directly!

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
Did you know that in the latest update, you can play as the Wither Storm?

**Comment by lonely734** [comment]
cool

**Comment by Composer-Hu** [comment]
Oh really!? So amazing!

**Comment by Composer-Hu** [comment]
Can you make the 0~3 stage more restored to MCSM? Only the wither flaming skull is shot instead of wither skull?[https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1008](url) I once proposed this to cracker, but I don't think he's going to take that opinion

**Comment by Composer-Hu** [comment]
We'll try to promote it as much as possible to get more people to support you.

**Comment by WitherBean** [comment]
Do you mean remove the normal wither skull entirely or turn the wither into the flaming wither skull?

**Comment by WitherBean** [comment]
In the next update the flaming wither skull will be shot more, but I cannot do this in the later states yet.

**Comment by Composer-Hu** [comment]
Be like MCSM,no any wither skull, just flaming wither skull, includes stages 0-3.By the way ,I hope flaming wither skull will be just in a very short cool down time, maybe each head is basically fired every five seconds like MCSM?In this way, the current enhancement of the flaming wither skull can be canceled. Thank you.

**Comment by WitherBean** [comment]
I can do this, but it will be in the next update.

**Comment by Composer-Hu** [comment]
Thank you can do this, I will keep looking forward and waiting for the next update.

**Comment by WitherBean** [comment]
I just finished this.

**Comment by Composer-Hu** [comment]
With such high efficiency, you are absolutely a god!

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
Check the description.

**Comment by Composer-Hu** [comment]
sorry, I don't understand what this means, where I can check?

**Comment by WitherBean** [comment]
https://www.curseforge.com/minecraft/texture-packs/bwsb-better-wither-storm-bowels-and-more has had a small update (not a release version) in the description tab.

**Comment by Composer-Hu** [comment]
Ok, thank you.

**Comment by WitherBean** [comment]
Your welcome, the update will be released later.

**Comment by Composer-Hu** [comment]
Thanks again!

**Comment by WitherBean** [comment]
You're welcome!

**Comment by Composer-Hu** [comment]
Excuse me, can you do some optimization? I mean I hope creatures can fly into the mouth of the wither storm and not on the body, the main thing is that the sound of bite is not heard now haha. And some more optimization is about the wither storm segment，if it can participate in the absorption of organisms, like a wither storm, that would be better, but it wasn't very important, Thank you.

**Comment by WitherBean** [comment]
I will try this, but it will be in the next update if it works.

**Comment by WitherBean** [comment]
Right now, I am working on nocking the player back for the formidibomb.

**Comment by WitherBean** [comment]
An alpha build of the datapack is going to be released!

**Comment by lonely734** [comment]
:)

**Comment by Composer-Hu** [comment]
Thank you

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
It will be released in a few minutes.

**Comment by Composer-Hu** [comment]
Good!

**Comment by lonely734** [comment]
I can't wait:)

**Comment by WitherBean** [comment]
The Withered Symbiont has the abilities in the beta (not released yet).

**Comment by Composer-Hu** [comment]
You're great enough

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
In this alpha, there is more than expected...

**Comment by WitherBean** [comment]
It has been released!

**Comment by Composer-Hu** [comment]
Download successfully, I can't wait to try it！

**Comment by WitherBean** [comment]
This might be big news but, I am going to release a new Witherstormmod New Textures beta too.

**Comment by Composer-Hu** [comment]
OK!

**Comment by WitherBean** [comment]
It will be out in a few minutes...

**Comment by Composer-Hu** [comment]
You are the real God！

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
This will be added in the full version: https://github.com/nonamecrackers2/crackers-wither-storm-mod/pull/644

**Comment by Composer-Hu** [comment]
Great!

**Comment by WitherBean** [comment]
How is the update?

**Comment by Composer-Hu** [comment]
I can't belive it's so amazing, it's getting more and more perfect! There is only one problem, and that is command blocks glow white smoke, It's hard for me to see where it is in the bowles. And I hoping for next update It will be found that the flaming wither skull will be shot continuously!

**Comment by Composer-Hu** [comment]
Thank you again!

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
The new update will have changes to the formidibomb too.

**Comment by Composer-Hu** [comment]
Ok！And I found some problems, when the withering storm enters the suspended animation phase, the wither storm segment will coincide with the wither storm, And when they(wither storm segment) wake up, they will turn their backs to the player and look back, but they will fly forward.

**Comment by Composer-Hu** [comment]
And yes! I found cases where flaming wither skull were frequently ejected. But this intensive attack scenario only occurred in stage 6.5,(Maybe it's too dense now haha) can you make it do that after 4 stages? Then the first three stages are also capable of firing flaming wither  skull more frequently.Thank you！

**Comment by lonely734** [comment]
Are you still there?

**Comment by WitherBean** [comment]
I did not see these problems because I was sleeping.

**Comment by Composer-Hu** [comment]
No problem, you should rest.

**Comment by WitherBean** [comment]
The tractor beams' speed have been increased.

**Comment by Composer-Hu** [comment]
That's so great!

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
Just like how you requested in Cracker's Wither Storm Mod, players are sucked in slower.

**Comment by Composer-Hu** [comment]
And then other organisms will be quickly inhaled?

**Comment by WitherBean** [comment]
Yes, they will.

**Comment by Composer-Hu** [comment]
You're really very awesome！

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
> And yes! I found cases where flaming wither skull were frequently ejected. But this intensive attack scenario only occurred in stage 6.5,(Maybe it's too dense now haha) can you make it do that after 4 stages? Then the first three stages are also capable of firing flaming wither skull more frequently.

I unfortunately cannot increase the fire-rate of the flaming wither skulls.

**Comment by Composer-Hu** [comment]
But why is it that in phase 6.5, and only this only stage, the rate of fire of the wither storm is very fast? Only after yesterday's new update. That's very interesting, maybe it just triggered something ?haha, flaming wither skulls you can leave it alone.

**Comment by WitherBean** [comment]
I am not sure why, It might be because of the heads being active.

**Comment by Composer-Hu** [comment]
It's okay, you've done a great job! You don't have to meet all our requirements.

**Comment by WitherBean** [comment]
Thank you!

**Comment by WitherBean** [comment]
The Withered Symbiont heals with block clusters.

**Comment by Composer-Hu** [comment]
Great！I'm going to bed, but I'm looking forward to the update！

**Comment by WitherBean** [comment]
BWSB 3.0.0 is coming out soon.

**Comment by Composer-Hu** [comment]
Thank you, you worked hard！

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
It has been released.

**Comment by Composer-Hu** [comment]
Great！

**Comment by Composer-Hu** [comment]
You really made the withering storm very powerful, I love it! I want to give a variety of positive reviews for my first experience！And Thank You Again！

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
I will close this issue, if there are any more please let me know.

**Comment by lonely734** [comment]
ok
