### ISSUE TITLE
Sorry to tell you this

### ISSUE THREAD

**Issue by Composer-Hu** [blarp5090/BWSB#21]
This update does not work at all in version 1.19.3, although I have tried various approaches: Download the latest pehkui mod, create different new worlds to experiment, download the data package again on your website. But to no avail.

**Comment by WitherBean** [comment]
Try again once the new Witherstormmod New Textures is released.

**Comment by Composer-Hu** [comment]
ok.

**Comment by WitherBean** [comment]
Witherstormmod New Textures has been updated.

**Comment by Composer-Hu** [comment]
Okay, I'll try it first.

**Comment by Composer-Hu** [comment]
Sorry, the resource pack works very well, but the datapack doesn't work at all.

**Comment by WitherBean** [comment]
I will release an update soon that should fix this problem, but try installing the guard villagers mod for 1.19.3.

**Comment by Composer-Hu** [comment]
Yes, I use this mod all the time. I tried to fix it with 4.5.0, and it worked.

**Comment by WitherBean** [comment]
Enable the Guard Villagers mod for 1.19.3, that is how I fixed it for me.
