### ISSUE TITLE
Dimmer Night Glare

### ISSUE THREAD

**Issue by NinjaSam5399** [blarp5090/BWSB#24]
The night glare should be dimmer/mostly transparent instead of looking like a non-transparent blue oval behind the wither storm.

**Comment by Composer-Hu** [comment]
This cannot be modified because the aperture has a base color, which is purple. If the map is more transparent, the purple color it will be more pronounced.

**Comment by NinjaSam5399** [comment]
I don't think this is a bug.

**Comment by WitherBean** [comment]
New Witherstormmod New Textures update for this.
