### ISSUE TITLE
The datapack fails to load

### ISSUE THREAD

**Issue by jojofenin99** [blarp5090/BWSB#27]
here is the log: [https://mclo.gs/rotX594](url)

**Comment by WitherBean** [comment]
I cannot access the log.

**Comment by WitherBean** [comment]
But, try this: disable the datapack and enter the world. Then, enable the datapack again.

**Comment by jojofenin99** [comment]
ok, also this link might work https://mclo.gs/RN4JZGf

**Comment by WitherBean** [comment]
What version of the datapack is this?

**Comment by WitherBean** [comment]
And also what version of Minecraft is this?

**Comment by jojofenin99** [comment]
it is version 5.1.0 of the data pack and it is 1.19.4 (45.0.59) of mc

**Comment by WitherBean** [comment]
Is it just in this version?

**Comment by jojofenin99** [comment]
should I try another version?

**Comment by WitherBean** [comment]
Yes, it may just be a problem with that one version.

**Comment by jojofenin99** [comment]
it still crashed

**Comment by WitherBean** [comment]
Are you able to make a screen recording and share it here?

**Comment by jojofenin99** [comment]
wait is this data pack server compatible

**Comment by WitherBean** [comment]
I am not sure, but try to use a singleplayer world first.

**Comment by jojofenin99** [comment]
When i try single player it says datapack validation failed

**Comment by WitherBean** [comment]
Disable it and re-enable it inside the world.
