### ISSUE TITLE
Hole Problem 

### ISSUE THREAD

**Issue by Magiciandseq3** [blarp5090/BWSB#28]
Hello, I had a question in your datapack. A hole is opened when Wither Storm phase 0, how do I fix this problem or can you fix this problem pls?

**Comment by WitherBean** [comment]
What version of BWSB are you using?

**Comment by Magiciandseq3** [comment]
I tried in 2 versions bwsb 4.0.0 and 4.0.0 Bug fix but I have the same problem in both. My Minecraft version is 1.19.3

**Comment by Magiciandseq3** [comment]
![image](https://github.com/WitherBean/BWSB/assets/137506666/6bf6c9ba-f8ad-4a8b-a64d-628be6d9cbe1)

**Comment by WitherBean** [comment]
Use BWSB: 5.0.0 (1.19.3).

**Comment by Magiciandseq3** [comment]
but in bwsb 5.0.0 bowels are not rotate

**Comment by WitherBean** [comment]
Enable the Guard Villagers mod.
I am updating the datapack again, and it should be fixed then.

**Comment by WitherBean** [comment]
Re-open this if it still doesn't work after that.
