### ISSUE TITLE
problems with basically everything

### ISSUE THREAD

**Issue by LetThereBeCarnage2106** [blarp5090/BWSB#29]
heya, I put in the datapack, it says it's in but half of the features aren't working. is optifine optional? cuz thats the only thing I don't have because I can't figure it out. the block doesn't go to the ceiling, the weather effects don't happen, can't ride the storm heads in the bowels(or anywhere for that matter) and none of the extra effects happen when I hit the command block. the only time the bowels falls apart is when I use the function command for it. resource pack works fine, just the datapack,

**Comment by WitherBean** [comment]
The weather effects need optifine.

**Comment by WitherBean** [comment]
What version of the datapack are you using?

**Comment by Magiciandseq3** [comment]
I HAVE THE SAME PROBLEM İN 5.0.0

**Comment by WitherBean** [comment]
Enable the Guard Villagers mod.
