### ISSUE TITLE
Resource Pack Validation Failed for BWSB 5.1.0

### ISSUE THREAD

**Issue by CrazyDog872** [blarp5090/BWSB#30]
When i try to put in the data pack upon world creation, it says "resource pack validation failed". I tried to import the data pack after world creation and same issue. Idk what to do, it would be great to know what im doing wrong, thanks.
1.19.4 forge, with CWSM and extra mods that could be possibly interfering.

**Comment by WitherBean** [comment]
What mods do you have?

**Comment by CrazyDog872** [comment]
Sorry I noticed my typo, I meant to say that I have tried this without any other mods besides CWSM

**Comment by WitherBean** [comment]
Did you use /datapack enable/disable?

**Comment by CrazyDog872** [comment]
No, i havent. I'll try it

**Comment by CrazyDog872** [comment]
So while I have gotten it to show up working via "/datapack list", and the fact that i can do "/function bwsb:" I just dont see any of the features working. And i noticed that upon leaving and rejoining the world, the datapack is disabled. And when I check the datapack version, it for some reason says 5.0.0. Even though I have downloaded the 5.1.0 file.

**Comment by WitherBean** [comment]
It saying 5.0.0 is a bug, but try BWSB:5.0.0.

**Comment by CrazyDog872** [comment]
isnt working either. I tried 3.0.0 and is working, however im curious about why i get glitched into the bowel heads when i get close

**Comment by WitherBean** [comment]
Enable the Guard Villagers mod.
