### ISSUE TITLE
Command block does not turn upside down 

### ISSUE THREAD

**Issue by MrIcecream00** [blarp5090/BWSB#31]
Hey, I have recently discovered this datapack and all the commands work just fine the only problem I am running into, is that the command block is not flipping in the end fight. I am playing on 1.19.3 btw. Is there any fix for that?
![Bild_2023-07-12_211037065](https://github.com/WitherBean/BWSB/assets/109606144/7308e5fe-ebba-434f-b98d-ec57e553f525)
![Bild_2023-07-12_211109065](https://github.com/WitherBean/BWSB/assets/109606144/6dfb694b-1799-4252-9ddf-62069b0e7190)
![Bild_2023-07-12_211146343](https://github.com/WitherBean/BWSB/assets/109606144/327b92ff-ca1e-43c1-8876-fd49877bf71c)

**Comment by WitherBean** [comment]
Enable the Guard Villagers mod.
