### ISSUE TITLE
what

### ISSUE THREAD

**Issue by lightingtay12** [blarp5090/BWSB#34]
so i got a world in chat it says some idk

**Comment by WitherBean** [comment]
What mods/resourcepacks do you have installed?

**Comment by WitherBean** [comment]
Scince, this is just an Optifine problem, I highly suggest to use replacements/alternatives for that mod.

**Comment by WitherBean** [comment]
Use entity texture features and entity model features instead.

**Comment by lightingtay12** [comment]
> What mods/resourcepacks do you have installed?

i have the wither storm mod pehnk and idk

**Comment by lightingtay12** [comment]
> Scince, this is just an Optifine problem, I highly suggest to use replacements/alternatives for that mod.

what can i use?

**Comment by WitherBean** [comment]
> > Scince, this is just an Optifine problem, I highly suggest to use replacements/alternatives for that mod.
> 
> what can i use?

Entity Texture Features and Entity Model Features.

**Comment by lightingtay12** [comment]
> > > Scince, this is just an Optifine problem, I highly suggest to use replacements/alternatives for that mod.
> > 
> > 
> > what can i use?
> 
> Entity Texture Features and Entity Model Features.

do i need them?

**Comment by WitherBean** [comment]
> > > > Scince, this is just an Optifine problem, I highly suggest to use replacements/alternatives for that mod.
> > > 
> > > 
> > > what can i use?
> > 
> > 
> > Entity Texture Features and Entity Model Features.
> 
> do i need them?

no

**Comment by WitherBean** [comment]
> > > > Scince, this is just an Optifine problem, I highly suggest to use replacements/alternatives for that mod.
> > > 
> > > 
> > > what can i use?
> > 
> > 
> > Entity Texture Features and Entity Model Features.
> 
> do i need them?

for a new update (not released) you will

**Comment by lightingtay12** [comment]
> > > > > Scince, this is just an Optifine problem, I highly suggest to use replacements/alternatives for that mod.
> > > > 
> > > > 
> > > > what can i use?
> > > 
> > > 
> > > Entity Texture Features and Entity Model Features.
> > 
> > 
> > do i need them?
> 
> for a new update (not released) you will

will it get released soon?

**Comment by WitherBean** [comment]
yes

**Comment by WitherBean** [comment]
closing until needed to reopen
