### ISSUE TITLE
I can't install the mod correctly, help

### ISSUE THREAD

**Issue by Gurbuz24** [blarp5090/BWSB#37]
Hello, I installed the modpack and put it in the resourcepack file and activated it in the game, but witherstorm's eyes are white and the intestines are not turning upside down, can you help?

**Comment by WitherBean** [comment]
You just installed the resourcepack. Go to here https://www.curseforge.com/minecraft/texture-packs/wwst-witherbeans-wither-storm-tweaks/files/4870346. Download the file, then go into your your modpack, click one of the three dots (if you are using curseforge) and click "open folder". Go into your world's folder and put the file in the "datapacks" folder.

If you are using Minecraft's folder, go into saves, then go into your worlds, then go into the datapacks folder and put the file in there.


Once you have done these steps, go into your world, and type "/reload" in chat.

**Comment by Gurbuz24** [comment]
> Kaynak paketini yeni yüklediniz. Buraya gidin https://www.curseforge.com/minecraft/texture-packs/wwst-witherbeans-wither-storm-tweaks/files/4870346 . Dosyayı indirin, ardından mod paketinize gidin, üç noktadan birine tıklayın (eğer Curseforge kullanıyorsanız) ve "Klasörü aç"a tıklayın. Dünyanızın klasörüne gidin ve dosyayı "datapacks" klasörüne koyun.
> 
> Minecraft klasörünü kullanıyorsanız, kayıtlara gidin, ardından dünyalarınıza gidin, ardından datapacks klasörüne gidin ve dosyayı oraya koyun.
> 
> Bu adımları tamamladıktan sonra dünyanıza gidin ve sohbete "/reload" yazın.

Will the file be kept in the resource pack?

**Comment by WitherBean** [comment]
you can keep the resourcepack file

**Comment by Gurbuz24** [comment]
> kaynak paketi dosyasını saklayabilirsiniz

It still doesn't work. When I make /datapack list in the game, the file appears but it doesn't work. How can it be activated?

**Comment by Gurbuz24** [comment]
> /datapack "dosya/BWSB"yi etkinleştir

![2024-02-28_19 02 02](https://github.com/WitherBean/BWSB/assets/161587219/132979bb-5853-4684-ab1c-c337303639de)
It says the command is incorrect

**Comment by WitherBean** [comment]
you need the quotes

**Comment by Gurbuz24** [comment]
quotation?

**Comment by WitherBean** [comment]
**/datapack enable "file/BWSB"**

The bolded parts are needed.

**Comment by Gurbuz24** [comment]
So how do I do it?

**Comment by WitherBean** [comment]
copy and paste this in chat: /datapack enable "file/BWSB"

**Comment by Gurbuz24** [comment]
I'm getting an unknown data packet error.

**Comment by WitherBean** [comment]
screenshot please

**Comment by Gurbuz24** [comment]
![2024-02-28_19 16 53](https://github.com/WitherBean/BWSB/assets/161587219/134a0f42-a9f3-49fc-a787-bbb1f94883c1)
error

**Comment by WitherBean** [comment]
what does your datapacks folder look like?

**Comment by Gurbuz24** [comment]
![image](https://github.com/WitherBean/BWSB/assets/161587219/92489f9f-e595-4776-89aa-8ec2204a8f39)

**Comment by WitherBean** [comment]
Use this link and download the file on there and replace the zip file with this one https://www.curseforge.com/minecraft/texture-packs/wwst-witherbeans-wither-storm-tweaks/files/4870346

**Comment by Gurbuz24** [comment]
ok i'm trying

**Comment by Gurbuz24** [comment]
![2024-02-28_19 29 21](https://github.com/WitherBean/BWSB/assets/161587219/e444dda4-a3dc-4dc6-838b-651c54ab8c00)
I guess it's active, huh? what should I do?

**Comment by WitherBean** [comment]
nothing. The datapack is installed.
