### ISSUE TITLE
BWSB Lag Bug

### ISSUE THREAD

**Issue by C-4-N** [blarp5090/BWSB#39]
When you have Withered Nether Star in your hand and you drop it (with Q) it multiplies and causes lag. (Because when you gain the Withered Nether Star in BWSB, it generates some falling blocks and Command Block that falls to the ground. and It Repeats itself. Causing lag, Generating Infinite Blocks and Giving You more Withered Nether Starts.)

**Comment by WitherBean** [comment]
This will be fixed in the Destruction Update.
