### ISSUE TITLE
A request for sky rendering

### ISSUE THREAD

**Issue by Composer-Hu** [blarp5090/BWSB#4]
There is already a night render in the resource pack, and it works very well, But during the day, the sky is far less color-rendered than the oppressive feeling at night, So can I ask you to add a rendering of the sky that also has dark colors during the day? Although they are all in the day, it is also as dark as the night. Just like in MCSM, the Redstonenia stage already has a very dark sky rendering at the beginning, In formidibomb battles, it turns into a deep purple sky rendering! Thank you！

**Comment by WitherBean** [comment]
I believe that I can do this, but it will also darken the night sky too.

**Comment by Composer-Hu** [comment]
Great, Thank you!

**Comment by WitherBean** [comment]
You're welcome!

**Comment by lonely734** [comment]
![Screenshot_20230314_232303_tv danmaku bili](https://user-images.githubusercontent.com/127328952/225050514-6210337b-047f-454d-9b75-94c821936bd1.jpg)
Can you change the sky like this?

**Comment by WitherBean** [comment]
Yes I can, but it will be in the next update.

**Comment by lonely734** [comment]
That would be great！

**Comment by lonely734** [comment]
![Screenshot_20230314_233005_tv danmaku bili](https://user-images.githubusercontent.com/127328952/225053055-b2277860-fa50-428b-9bf0-db1089e73226.jpg)
Maybe you can change the glare of the storm by the way, like this:

**Comment by WitherBean** [comment]
I probably could, I know where the file is.

**Comment by Composer-Hu** [comment]
Yes, I think the color of the cracker is too dark now, and the purple color is too heavy, Thank you again！

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
In the next update, this will be updated.

**Comment by Composer-Hu** [comment]
You're Awesome!

**Comment by WitherBean** [comment]
Thank you!
