### ISSUE TITLE
Suggestion for BWSB

### ISSUE THREAD

**Issue by C-4-N** [blarp5090/BWSB#40]
Wither Storm's Flying Height must Change according to Player's Y Coordinate

**Comment by WitherBean** [comment]
What do you mean by this?

**Comment by C-4-N** [comment]
> What do you mean by this?

I mean if you are on a high Mountain, You and Wither Storm would be in a Same level/line right? Wither Storm have to look Menacing, so I mean If you see Wither Storm higher than you it would be more menacing and good

**Comment by C-4-N** [comment]
> > What do you mean by this?
> 
> I mean if you are on a high Mountain you and Wither Storm would be in a Same level/line right? Wither Storm have to look Menacing, so I mean If you see Wither Storm higher than you it would be more menacing and good

Since It's Flying Height can only be changed manually

**Comment by WitherBean** [comment]
Will be implemented in the next major release.
