### ISSUE TITLE
Command Block Recipe Change and Command Block Texture

### ISSUE THREAD

**Issue by C-4-N** [blarp5090/BWSB#42]
New Command Block recipe that is harder. Like it could use some Redstone, Copper, Nether Star, etc. I don't know really but its so easy to craft it. Also you could also implement old texture style of Command Block to Chain and Repeat Command Blocks too. Also Wither Storm's Phase 0, 1, 2 shows Programmer Art's Command Block too. I don't know it's intentional or mistake tho

**Comment by WitherBean** [comment]
"Also Wither Storm's Phase 0, 1, 2 shows Programmer Art's Command Block too. I don't know it's intentional or mistake tho"
That's intentional.

**Comment by WitherBean** [comment]
"New Command Block recipe that is harder. Like it could use some Redstone, Copper, Nether Star, etc. I don't know really but its so easy to craft it. Also you could also implement old texture style of Command Block to Chain and Repeat Command Blocks too." will be added

**Comment by WitherBean** [comment]
Will be implemented in the next major release.
