### ISSUE TITLE
BWSB Lag Problem

### ISSUE THREAD

**Issue by C-4-N** [blarp5090/BWSB#43]
Wither Storm teleports randomly or it's just going way too fast that we can't see it, I don't know. Also Wither Storm takes so many blocks (Clusters) from the ground at the same time and It causes really really bad lag

**Comment by WitherBean** [comment]
The teleporting is an error when the Wither Storm tries to use its charge attack.

**Comment by Gurbuz24** [comment]
I have lag problem too, it happens when datapack is activated.

**Comment by WitherBean** [comment]
Will be fixed in the next major release.
