### ISSUE TITLE
How to fix the mod

### ISSUE THREAD

**Issue by emrearas14** [blarp5090/BWSB#45]
Maybe actually fucking fix the mod blud literally no one can play your mod, in 1.20.1 its completely broken the data pack doesnt work at all and bowel flipping is broken too, FIX YOUR MOD

**Comment by emrearas14** [comment]
Also make a tutorial how to correctly install it or something cause i might've got it wrong

**Comment by WitherBean** [comment]
You did it wrong. I was working on a tutorial.

**Comment by emrearas14** [comment]
Sorry for the meltdown but i know theres a tutorial but it doesn't work cause maybe it's old but next time you make a tutorial can you show like what to do fully? like a full tutorial

**Comment by emrearas14** [comment]
Can you at least tell me which file is the datapack for 1.19.4

**Comment by WitherBean** [comment]
The datapack is actually for 1.19.4. WNT is the resourcepack. BWSB is the datapack.

**Comment by emrearas14** [comment]
Oh ok it works but one thing i gotta suggest
