### ISSUE TITLE
Data Pack, how can I make the bowels turn upside down

### ISSUE THREAD

**Issue by Magiciandseq3** [blarp5090/BWSB#48]
Data Pack, how can I make the bowels turn upside down, I don't need others, please help me, I just want the bowels to turn upside down.

**Comment by WitherBean** [comment]
Did you install the datapack correctly?

**Comment by Magiciandseq3** [comment]
I downloaded the datapack properly, but because there is a lot of lag and because the bowels are inverted in the datapack, which I am very interested in, so I want it to be lag-free and  just bowels inverte My English is very bad, sorry if there are any mistakes

**Comment by WitherBean** [comment]
The bowels stuff is redone and the lag is fixed in the new update coming soon.

**Comment by Magiciandseq3** [comment]
which files are used to invert the bowels? 
please tell me, I will delete all but the files that make bowels invert until I wait for the update

**Comment by WitherBean** [comment]
It's in the top of tick.mcfunction

**Comment by Magiciandseq3** [comment]
If I delete everything in the data pack, is it okay if I don't just delete the rotation in the function section?

**Comment by WitherBean** [comment]
delete everything in tick.mcfunction under line 24

**Comment by WitherBean** [comment]
check the milestones to see the progress in the update and feel free to make more suggestions

**Comment by Magiciandseq3** [comment]
Will it work if I delete these files?
![image](https://github.com/WitherBean/BWSB/assets/137506666/2b8d38a0-3fa9-455c-8558-0ee4c967763c)

**Comment by WitherBean** [comment]
no

**Comment by Magiciandseq3** [comment]
Ok I wıll not delete those files thank you for help
:)

**Comment by WitherBean** [comment]
no problem
