### ISSUE TITLE
About Flaming Wither Skulls

### ISSUE THREAD

**Issue by Composer-Hu** [blarp5090/BWSB#5]
In the last packet update, I found in stage 6.5, The property of the skull being continuously shot it's still there,that's very interesting. If you are free, can I ask you to look into what causes this and make it possible at any other stage. Thank you.

**Comment by WitherBean** [comment]
I believe that this is either because when the Wither Storm gets 9 heads it shoots fireballs out of the new heads or because it has more chances to shoot the fireballs with more heads.

**Comment by Composer-Hu** [comment]
It doesn't just fire a lot of skulls because of the newly grown head, it will also be at an uncertain moment later in stage 6.5, a large number of skulls will be shoot in succession, and it lasts for a few minutes. If you don't like this issue you can close it, thank you.

**Comment by WitherBean** [comment]
I am not sure why this happens if it is not just because of the new heads.

**Comment by Composer-Hu** [comment]
Ok

**Comment by WitherBean** [comment]
In the next update, the bowels portal will appear lower.

**Comment by Composer-Hu** [comment]
Good！
