### ISSUE TITLE
witherstorm phase 1 to phase 5.5 may have the same darkening

### ISSUE THREAD

**Issue by Magiciandseq3** [blarp5090/BWSB#51]
Hello, I had a suggestion for you, I think witherstorm phase 1 to phase 5.5 may have the same darkening and those in phase 6 and 7 may be darker, I think that would be very nice.

**Comment by WitherBean** [comment]
Cracker's Wither Storm Mod does not support this yet.

**Comment by Magiciandseq3** [comment]
Would it support phases 6 and 7 if they were not darker and all had the same darkness?

**Comment by WitherBean** [comment]
Yes, but it does not give the same level of intimidation.

**Comment by Magiciandseq3** [comment]
So can I do that on my own now?

**Comment by Magiciandseq3** [comment]
I dreamed it would be like that :)

**Comment by WitherBean** [comment]
You can change 5-7

**Comment by Magiciandseq3** [comment]
Do I need to change this from the Crackers Wither Storm mod?

**Comment by WitherBean** [comment]
I think there is some sky configs in the next update for cwsm, you could try with any phase then.

**Comment by WitherBean** [comment]
@Magiciandseq3 You could also try submitting a bug report or a feature request in CWSM's issues tab.

**Comment by Magiciandseq3** [comment]
Thank you so Much:)

**Comment by WitherBean** [comment]
No problem!

**Comment by Magiciandseq3** [comment]
I beg you, can you teach me how to make the weather dark in all phases? Thank you very much.

**Comment by Magiciandseq3** [comment]
because I couldn't do it :(

**Comment by Composer-Hu** [comment]
Please wait for the next major update.

**Comment by WitherBean** [comment]
What did you try so far? You could try to retexture rain or thunder.

**Comment by Magiciandseq3** [comment]
So far I've tried looking for codes that include phase 5 and 7 and darkening.

**Comment by WitherBean** [comment]
try making it rain for phases and retexture the rain.

**Comment by Composer-Hu** [comment]
In Cracker‘s GitHub WiKi，you can find all of them.

**Comment by Magiciandseq3** [comment]
Thank you so much Composer-Hu and WitherBean

**Comment by Magiciandseq3** [comment]
ı will try

**Comment by Composer-Hu** [comment]
https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/1886，And about this, unfortunately Cracker rejected Phase1-4's suggestion to change color.

**Comment by Magiciandseq3** [comment]
Hello, can you tell me if there is a command to darken the air?

**Comment by Magiciandseq3** [comment]
And what is the code to make the weather day when the Wither storm dies, I will write it in the ticks section.

**Comment by Composer-Hu** [comment]
No any command, this is the resource part.

**Comment by Magiciandseq3** [comment]
![image](https://github.com/WitherBean/BWSB/assets/137506666/134c7295-d930-4abb-a23d-3100c3cedcef)
I will write the weather darkening command right here and it will be done.

**Comment by WitherBean** [comment]
> ![image](https://private-user-images.githubusercontent.com/137506666/328576486-134c7295-d930-4abb-a23d-3100c3cedcef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwOTQ4MTYsIm5iZiI6MTcxNTA5NDUxNiwicGF0aCI6Ii8xMzc1MDY2NjYvMzI4NTc2NDg2LTEzNGM3Mjk1LWQ5MzAtNGFiYi1hMjNkLTMxMDBjM2NlZGNlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxNTA4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjdkOWNlNWRkODY3ODE4NjI0NDkyZDRkZTc1OWZkZGQyMDBmNmJmNDA2MTIzZDQzNTE0MmE0YWRmYTFmNzEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HaSgOpwLvBjPik8T6MdZS3AhVmKkMMehpMLP7EON8dQ) I will write the weather darkening command right here and it will be done.

You are also using a very old datapack version.

**Comment by Magiciandseq3** [comment]
Merhabalar wither storm ölünce havanın gündüz olma komudu nedir? ve görseldeki havanın function komutu yada bir komutu varmı biliyorsanız lütfen yazı şimdiden çok teşekkürler:)
![image](https://github.com/WitherBean/BWSB/assets/137506666/af510ab7-6cad-49f7-a738-f88c6274f1bc)

**Comment by Magiciandseq3** [comment]
If you know of any commands or functions related to the sky in the image, please inform me. Also, if you know the command to instantly turn it into daytime when killing the Wither storm, please share. Thank you in advance.
![image](https://github.com/WitherBean/BWSB/assets/137506666/142173d9-a27d-4ebd-8db9-c0beac3874f4)

**Comment by WitherBean** [comment]
> If you know of any commands or functions related to the sky in the image, please inform me. Also, if you know the command to instantly turn it into daytime when killing the Wither storm, please share. Thank you in advance. ![image](https://private-user-images.githubusercontent.com/137506666/328628654-af510ab7-6cad-49f7-a738-f88c6274f1bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDcwMDgsIm5iZiI6MTcxNTEwNjcwOCwicGF0aCI6Ii8xMzc1MDY2NjYvMzI4NjI4NjU0LWFmNTEwYWI3LTZjYWQtNDlmNy1hNzM4LWY4OGM2Mjc0ZjFiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxODMxNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjA0YTY4M2UxYTlmNTc0Zjc3NWVhZjM2NDc4M2VhMTU1MzkwOTI3ZTE0YmI0OWNmMTZhNWZhMDc4ZDlhNGEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dB1pozRR1wdcUjyfMkS7SpfzI_yxgwAWneMY-6u6eO4)

It is hardcoded in cracker's mod.

**Comment by WitherBean** [comment]
> If you know of any commands or functions related to the sky in the image, please inform me. Also, if you know the command to instantly turn it into daytime when killing the Wither storm, please share. Thank you in advance. ![image](https://private-user-images.githubusercontent.com/137506666/328639697-142173d9-a27d-4ebd-8db9-c0beac3874f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMDc3NzUsIm5iZiI6MTcxNTEwNzQ3NSwicGF0aCI6Ii8xMzc1MDY2NjYvMzI4NjM5Njk3LTE0MjE3M2Q5LWEyN2QtNGViZC04ZGI5LWMwYmVhYzM4NzRmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwN1QxODQ0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kY2VlMjlkOWI0ODYzNmVlZjc0MGM2YmY1ZjhiMDExNDNjNzQyYjFjMzAzN2U3ODRiZThkMzEzM2Y5MjA1NDk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Gn66gphbcmhzhiUMiME4XyvzzIOyJmWt03QUixHVCsY)

/time set day

**Comment by Magiciandseq3** [comment]
Do you have any information on how to use Optifine with crackers wither storm?

**Comment by WitherBean** [comment]
Yes, use other mods. Entity Model Features and Entity Texture Features

**Comment by Magiciandseq3** [comment]
For some reason, keeps crashing even though I only have the pehkui crackers wither storm mod, Optifine, and the mods you mentioned, but it still keeps crashing:(

**Comment by WitherBean** [comment]
Remove Optifine.

**Comment by WitherBean** [comment]
Also please make this another bug report.
