### ISSUE TITLE
Cant Download Optifine

### ISSUE THREAD

**Issue by Magiciandseq3** [blarp5090/BWSB#52]

**Comment by Magiciandseq3** [comment]
I cant use Optifine with Cwsm I want withered sun but ı cant download optifine it keeps crashing

**Comment by WitherBean** [comment]
Optifine is no longer supported.

**Comment by Magiciandseq3** [comment]
I changed the texture of the rainy weather to purple, do I need Optifine for this, or can I do it without Optifine? How can I add it to the game?

**Comment by WitherBean** [comment]
> I changed the texture of the rainy weather to purple, do I need Optifine for this, or can I do it without Optifine? How can I add it to the game?

You can look for tutorials, I don't think you need optifine.

**Comment by Magiciandseq3** [comment]
Ohh ok Thank you:)

**Comment by WitherBean** [comment]
No problem!
