### ISSUE TITLE
I want the weather to be clear when I move away from the wither storm

### ISSUE THREAD

**Issue by Magiciandseq3** [blarp5090/BWSB#53]
Hello Witherbean, can I ask something? I want the weather to be clear when I move away from the wither storm. How can I do it? I tried to write this code execute if entity @e[type=witherstormmod:wither_storm,nbt={distance=..50}] run weather clear?
![image](https://github.com/WitherBean/BWSB/assets/137506666/19c92280-da6a-4635-970b-decc9b36948c)

**Comment by WitherBean** [comment]
..50 is within 50 blocks. 50.. is outside of 50 blocks.
