### ISSUE TITLE
 how to show phase 5.5 and such with NBT command

### ISSUE THREAD

**Issue by Magiciandseq3** [blarp5090/BWSB#54]
Hello Wither Bean, can I ask you something? I managed to make it get dark using a mod, but there's an issue. I also want it to get dark in phase 5 and in phase 5.5, I was planning to use a special command in the mod to revert the sky color back to normal. However, I'm not sure how to show phase 5.5 and such with NBT commands.

**Comment by WitherBean** [comment]
Wait until the next major update for cwsm.

**Comment by WitherBean** [comment]
It should be tomorrow

**Comment by Magiciandseq3** [comment]
What will happen in the new update?

**Comment by WitherBean** [comment]
I can't answer that, ask cracker

**Comment by Magiciandseq3** [comment]
And I have done this much, have I done it well?
![image](https://github.com/WitherBean/BWSB/assets/137506666/8e65130e-cd5d-4ad3-9341-f5897b1b5d38)
![image](https://github.com/WitherBean/BWSB/assets/137506666/ab2c2ac8-3389-4c79-bc61-b6a0bac96881)

**Comment by WitherBean** [comment]
It's pretty good so far, these should not really be GitHub suggestions, I suggest posting questions here https://discord.gg/HjBJJwatJN

**Comment by Magiciandseq3** [comment]
Thank you:) Where can I ask my question on your Discord server?

**Comment by WitherBean** [comment]
https://discord.com/channels/1180304040895205396/1238239928538632232
