### ISSUE TITLE
Bowels boss fight

### ISSUE THREAD

**Issue by EnderBROpro4229** [blarp5090/BWSB#57]
I did everything as written in the wiki, but when the command block turns upside down and when I start hitting it, no matter how many times I hit or wait before hitting it, it does not go down, I hit it even during the flip but it did not help. **Version 1.20.1**. Please help me how to defeat it??

**Comment by WitherBean** [comment]
When you hit the command block for the last time, you should fall down the pit or get teleported out due to cwsm's code.

**Comment by WitherBean** [comment]
The wiki was outdated, I have updated it.

**Comment by EnderBROpro4229** [comment]
I know that after the last hit you need to go down into the pit, but the hit itself does not work, the command block does not react in any way.
There is another similar situation. When the command block turns over, the heads are activated (at that moment the block can be freely hit but no damage is done) and I destroy them, but after that the block closes and it cannot be hit in any way.

**Comment by WitherBean** [comment]
What bwsb version are you using? (Destruction 1, 2?)

**Comment by EnderBROpro4229** [comment]
I use 2

**Comment by WitherBean** [comment]
What's your mod list?

**Comment by EnderBROpro4229** [comment]
What do you mean?

**Comment by WitherBean** [comment]
What mods do you have installed?

**Comment by EnderBROpro4229** [comment]
ok give me a second

**Comment by EnderBROpro4229** [comment]
I have several mods that add something of their own, like create or farmers delight, but they have nothing to do with the Crackers wither storm mod

**Comment by WitherBean** [comment]
Do you have Pehkui, EMF, and ETF?

**Comment by EnderBROpro4229** [comment]
Yes

**Comment by EnderBROpro4229** [comment]
Maybe i should download the old version of Crackers wither storm or the old version of the datapack? For which version was the datapack created?

**Comment by WitherBean** [comment]
Try to run /kill @e[type=witherstormmod:tentacle]

Maybe more people in my discord server can help you.
https://discord.gg/v8XncYF8EW

**Comment by EnderBROpro4229** [comment]
The command helped, thanks! But is it in creative, if I'm in survival? Okay, I'll ask in your Discord server

**Comment by EnderBROpro4229** [comment]
Thanks again for the little help, if this is a bug please fix it.

**Comment by WitherBean** [comment]
It should be fixed soon.

**Comment by WitherBean** [comment]
> Thanks again for the little help, if this is a bug please fix it.

No problem!

**Comment by EnderBROpro4229** [comment]
OH MY GOD I KNOW WHAT'S WRONG OH MY GOD I'M SO STUPID I CAN KILL THE TENTACLES THAT SURROUND THE COMMAND BLOCK!
oh my god I'm stupid....

**Comment by EnderBROpro4229** [comment]
There was no bug here, I forgot that the mod gives this ability. I'm closing this question. Thanks for giving me a tip! Bye
