### ISSUE TITLE
About the texture of Command Blocks

### ISSUE THREAD

**Issue by Composer-Hu** [blarp5090/BWSB#7]
Hello, it's me again. In the future, can you make the command block look like the texture in MCSM? Has a distinct three-dimensional feel, like the following image. I tried to make changes, but I'm not capable enough to do so. What I know so far is the entity's command block is shared with the block model in Minecraft, so if you make changes, you need to make changes to the square model and texture in Minecraft, at the same time, the command block of the entity will also synchronously identify the new texture. If possible, can you make ordinary command blocks in Minecraft have a continuous particle effect like solid command blocks? (Has the effect of absorbing particles into the blocks, At the same time, the pulses in the nine squares of the block will have a circular rotation of light, this is already in the original version, just modifying the texture may cause it to be lost. Finally, it would be even better if it could be have a pulsing loop sound.) Thank you.
![263BE28E380D3710282B0494506FCBE5](https://user-images.githubusercontent.com/127498588/225906680-047178b6-269c-413f-995b-aae88f808d1c.jpg)

**Comment by WitherBean** [comment]
I am not sure if I can do that in this update, but I will try to make it.

**Comment by Composer-Hu** [comment]
Thank you for trying this!

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
I will keep this open as a reminder.

**Comment by Composer-Hu** [comment]
Good!

**Comment by WitherBean** [comment]
The model works, but it will be in the next update.

**Comment by Composer-Hu** [comment]
Thank You!

**Comment by WitherBean** [comment]
You're welcome!

**Comment by Composer-Hu** [comment]
![image](https://user-images.githubusercontent.com/127498588/226187074-dcbfafd3-73e1-4bb4-beea-b7b8781e5f18.png)
HI, I will add that the following block effect might look like this.

**Comment by Composer-Hu** [comment]
If there is scattered light like MCSM, 
![M`V{ G3%(BTKGH@NLR@7521](https://user-images.githubusercontent.com/127498588/226187332-7b843a9a-3a50-4bb9-ad37-06e82bea7f3e.png)
Maybe the following diagram can help you
![I`@YU(FN6NOMRVL}VP @N1O](https://user-images.githubusercontent.com/127498588/226187378-f9e2e605-7c9a-4f57-92a7-6463f46847ac.png)

**Comment by Composer-Hu** [comment]
![M`V{ G3%(BTKGH@NLR@7521](https://user-images.githubusercontent.com/127498588/226187432-d0006b28-5fb7-4291-b41a-cd04c62de398.png)

**Comment by WitherBean** [comment]
I have this added, but it is in the form of an emissive texture.

**Comment by Composer-Hu** [comment]
OK！That's also great. Can you add the sound of the pulse as well?

**Comment by Composer-Hu** [comment]
OK！That's also great. Can you add the sound of the pulse as well? And accompanied by absorbed particle effects.

**Comment by WitherBean** [comment]
I might be able to.

**Comment by Composer-Hu** [comment]
Thank you so much! Thank you so much for everything!

**Comment by WitherBean** [comment]
You're welcome!

**Comment by WitherBean** [comment]
This has been added in Witherstormmod New Textures 2.5.0.
