### ISSUE TITLE
lets talk about the Withered Sun

### ISSUE THREAD

**Issue by myron-obsolete-account** [blarp5090/BWSB#8]
i saw withered sun in the description of the mod. did you just straight up copy my idea without me even knowing about it? bro that sucks duh

**Comment by myron-obsolete-account** [comment]
if you didnt copy my idea then ok but why

**Comment by WitherBean** [comment]
I did not copy your idea and how would I know about it?

**Comment by myron-obsolete-account** [comment]
ok then its fine yeah idk maybe you couldve knwon about it by looking into the issues of the wither storm mod

**Comment by myron-obsolete-account** [comment]
this here https://github.com/nonamecrackers2/crackers-wither-storm-mod/issues/994

**Comment by WitherBean** [comment]
I did not know that existed.

**Comment by Composer-Hu** [comment]
It is quite normal to have similar ideas, and Witherbean just created a sky rendering that conforms to the storm theme.

**Comment by NinjaSam5399** [comment]
At least it was denied by the real wither storm mod.
